name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Racket
        run: |
          sudo apt-get update
          sudo apt-get install -y racket

      - name: Install dependencies
        run: |
          raco pkg install --auto --no-docs rebellion

      - name: Setup Racket libraries
        run: |
          raco setup

      - name: Run tests
        run: |
          make test