name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Meson
      run: sudo apt-get install -y meson ninja-build
    
    - name: Build
      run: meson setup builddir && meson compile -C builddir

    - name: Install dependencies
      run: bash install.sh

    - name: Test
      run: cd builddir && ./test_sumsum